spring:
  datasource:
    url: jdbc:h2:mem:db_delivery
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
server:
  port: 8081
weather:
  import:
    cron: "10 * * * * *"